# -*- mode: snakemake -*-

configfile:"config.yml"

rule all:
	"The default rule"
	input:
		fig_words=expand("../results/wordcloud_{condition}.png",condition=config["CONDITIONS"]),
		fig_bigrams=expand("../results/bigramcloud_{condition}.png",condition=config["CONDITIONS"])

rule setup:
	"setup"
	shell:"""
	mkdir -p ../results
	mkdir -p ../data/derived/intermediate/ 
	"""


rule:
	name:
		"side_effects_{condition}"
	input:
		"../data/original/drugLibTrain_raw.tsv"
	output:
		"../data/derived/intermediate/word_rankings_{condition}.csv"
	shell:
		"Rscript 1_find_side_effects.R {wildcards.condition}"

rule:
	name:
		"plot_{condition}"
	input:
		"../data/derived/intermediate/word_rankings_{condition}.csv"
	output:
		"../results/wordcloud_{condition}.png",
		"../results/bigramcloud_{condition}.png"
	shell:
		"Rscript 2_plot_wordcloud.R {wildcards.condition}"

rule clean:
	"Clean up"
	shell:"""
        if [ -d ../data/derived/intermediate ]; then
        rm -r ../data/derived/intermediate
        else
                echo directory intermediate does not exist
        fi
	if [ -d ../results ]; then
	rm -r ../results
	else
		echo directory results does not exist
	fi
	"""
